/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4sswn72nqngibbyjdvravba6ta.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-x2y3f6lum5grjkcyluotab7gba",
    "aws_cognito_identity_pool_id": "us-east-1:a2906d86-b9fe-4713-82e2-ca8093515076",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JEuSoGOqG",
    "aws_user_pools_web_client_id": "6l5qm7jl8quo37v715nvt6rgm5",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "ON",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Feeding",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
